version: '3.7'

networks:
  intranet:

services:
  discord-bot-service:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: discord-bot-service
    ports:
      - "9526:9526"
    env_file:
      - ./.env
    restart: on-failure
    # depends_on:
      # - scopes-db
      # - redis
    networks:
      - intranet

  # redis:
  #   image: redis:5.0.5-alpine
  #   container_name: dev-shared-redis
  #   restart: always
  #   environment:
  #     - "ENV=develop"
  #   ports:
  #     - "6379:6379"
  #   expose:
  #     - "6379"
  #   networks:
  #     - intranet

networks:
  intranet: 
    external:
      name: intranet
